const make = 'Mercedes';
const model = 'E350 Coupe`';
let hPw = 305;
let kW = 225;

const baby = (make, model, horsePower, kiloWatts) =>
  `Baby manufacturer  is ${make},
    The model: ${model},
    Current Horse Power: ${horsePower},
    KiloWatts generated by the Engine: ${kiloWatts}`;

document.querySelector('body').innerHTML = `<p>${baby(
  make,
  model,
  hPw,
  kW
)}</p>`;
